name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        api-level: [30]
        target: [default]
        abi: [x86]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Download dependencies
        run: ./gradlew build --no-daemon

      - name: Run Unit Tests
        run: ./gradlew test --no-daemon

      - name: Run Instrumentation Tests
        run: ./gradlew connectedAndroidTest --no-daemon
